# Generated by Django 6.0.2 on 2026-02-17 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=10)),
                ('number', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField(verbose_name='Дата рождения')),
                ('date_issue', models.DateField(verbose_name='Дата выдачи')),
            ],
            options={
                'verbose_name': 'Паспорт',
                'verbose_name_plural': 'Паспорта',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Должности',
                'verbose_name_plural': 'Должности',
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=150)),
                ('login', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('passport_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.passport')),
                ('position_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.position')),
            ],
            options={
                'verbose_name': 'Работник',
                'verbose_name_plural': 'Работники',
            },
        ),
    ]
